//
//  GrocerySection.swift
//  Takkellapati_GroceryApp
//
//  Created by Takkellapati,Venkata Prabhakar on 4/12/22.
//


import Foundation

struct Grocery {
var section = ""
var items_Array:[GroceryItem] = []
}

struct GroceryItem{
    var itemName = ""
    var itemImage = ""
    var itemInfo = ""
}

let groceryitem1 = Grocery(section:"Fruits",items_Array:[GroceryItem(itemName:"Mango",itemImage:"mango",itemInfo:"A mango is an edible stone fruit produced by the tropical tree Mangifera indica which is believed to have originated from the region between northwestern Myanmar, Bangladesh, and northeastern India.M. indica has been cultivated in South and Southeast Asia since ancient times resulting in two distinct types of modern mango cultivars: the Indian type and the Southeast Asian type."), GroceryItem(itemName: "Grapes", itemImage: "grapes", itemInfo: "People have cultivated grapes for thousands of years, including several ancient civilizations that revered them for their use in winemaking. Grapes also make a quick and delicious snack you can enjoy at home or on the go."), GroceryItem(itemName: "Grapes", itemImage: "grapes", itemInfo: "TAn apple is a sweet, edible fruit produced by an apple tree (Malus domestic). In France, it is the most consumed edible fruit and the third in the planet. The main types of apples come from the domestic apple or common apple. The species of Malus Domestica has about 20,000 varieties and cultivars around the world. The fruit has a characteristic stocky shape and often spherical, it is eaten when ripe, raw, cooked, or dried."), GroceryItem(itemName: "Banana", itemImage: "banana", itemInfo: "Bananas are great super food which provides us with energy, make us feel full and provide our body with essential nutrients and high amount of fiber. The scientific name of banana is Masa acuminata and Masa balbisiana.It is natural that we always mistake a banana for a plantain. Plantains are a member of the banana family. They are bigger in size and bright green."), GroceryItem(itemName: "WaterMelon", itemImage: "watermelon", itemInfo: "The cheery red color comes from lycopene, an antioxidant. Studies show it may help curb your risk of cancer and diabetes as part of a healthy lifestyle. Watermelon has more of this nutrient than any other fruit or veggie -- even tomatoes. To load up on lycopene, choose a melon with bright red flesh rather than yellow or orange. And the riper, the better.")] )

let groceryitem2 = Grocery( section: "Vegetables", items_Array: [GroceryItem(itemName: "Carrot", itemImage: "carrot", itemInfo: "Carrot helps employers and health plans provide equal access to high-quality fertility care regardless of age, race, income, sex, sexual orientation, gender identity, marital status, or geographic location"), GroceryItem(itemName: "Broccoli", itemImage: "brocolli", itemInfo: "Broccoli (Brassica oleracea) is a cruciferous vegetable related to cabbage, kale, cauliflower, and Brussels sprouts.These vegetables are known for their beneficial health effects.Broccoli is high in many nutrients, including fiber, vitamin C, vitamin K, iron, and potassium. It also boasts more protein than most other vegetables."), GroceryItem(itemName: "Cucumber", itemImage: "cucumber", itemInfo: "There are two types of cucumber plants: vining cucumbers and bush cucumbers. Vining cucumbers, the most common varieties, grow on vigorous vines shaded by large leaves. The growth of these plants is fast, and the crop yield is abundant if you care for them properly. Vining varieties grow best when trained up a trellis or fence. Since they grow off the ground, the fruits will be cleaner—versus those that grow "), GroceryItem(itemName: "Egg Plant", itemImage: "eggplant", itemInfo: "A serving of eggplant can provide at least 5% of a person’s daily requirement of fiber, copper, manganese, B-6, and thiamine. It also contains other vitamins and minerals.In addition, eggplants are a source of phenolic compounds that act as antioxidants.Antioxidants are molecules that help the body eliminate free radicals — unstable molecules that can damage cells if they accumulate in large amounts."), GroceryItem(itemName: "Green Pepper", itemImage: "greenpepper", itemInfo: "Green sweet peppers or bell peppers (Capsicum annuum) are commonly thought of as vegetables, though they’re technically a type of fruit (Trusted Source).Bell peppers have thick walls, are bell-shaped, and come in a variety of colors, including red, yellow, and purple.Green bell peppers are simply unripe bell peppers. They tend to be less sweet than red and yellow peppers and have a slightly bitter taste. ")] )

let groceryitem3 = Grocery( section: "Dals", items_Array: [GroceryItem(itemName: "RED Lentils", itemImage: "redlentils", itemInfo: "Each ¼ cup of dry red lentils (which makes ¾ cup when cooked) packs 9 grams of fiber and 13 grams of protein, plus roughly 25 percent of a day’s folate, 15 percent of a day’s iron, 14 percent of a day’s zinc, 9 percent of a day’s magnesium, and 6 percent of a day’s potassium. Not bad for 180 calories, zero sodium, and around 25 cents per serving."), GroceryItem(itemName: "Bengal Gram", itemImage: "bengalgram", itemInfo: "Bengal gram, closely related to the chickpea family, is a yellow lentil, rounded on one side and flat on the other.Bengal gram is one of the earliest cultivated legumes. In Indian cuisine, it is popularly known as Chana Dal."), GroceryItem(itemName: "Green Gram", itemImage: "green", itemInfo: "Bengal gram, closely related to the chickpea family, is a yellow lentil, rounded on one side and flat on the other.Bengal gram is one of the earliest cultivated legumes. In Indian cuisine, it is popularly known as Chana Dal."), GroceryItem(itemName: "Yelkow Pigeon Peas", itemImage: "yellow", itemInfo: "Also known as “toor dal,” Split Pigeon Peas are one of the most popular pulses in India. These hulled, split legumes break down easily when cooked, making them an ideal thickener for curries, soups and stews."), GroceryItem(itemName: "ChickPeas", itemImage: "chick", itemInfo: "Chickpeas boast an impressive nutritional profile.They contain a moderate number of calories, providing 269 per cup (164 grams). Approximately 67% of these calories come from carbs, while the rest comes from protein and fat (Trusted Source).Chickpeas also provide a variety of vitamins and minerals, as well as a decent amount of fiber and protein.")] )

let groceryitem4 = Grocery( section: "Soft Drinks", items_Array: [GroceryItem(itemName: "Coca Cola", itemImage: "coc", itemInfo: "Coca-Cola, or Coke, is a carbonated soft drink manufactured by the Coca-Cola Company. Originally marketed as a temperance drink and intended as a patent medicine, it was invented in the late 19th century by John Stith Pemberton in Atlanta, Georgia. In 1888 Pemberton sold Coca-Cola's ownership rights to Asa Griggs Candler, a businessman, whose marketing tactics led Coca-Cola to its dominance of the global soft-drink market throughout the 20th and 21st century."), GroceryItem(itemName: "Pepsi", itemImage: "pepsi", itemInfo: "Pepsi is a carbonated soft drink manufactured by PepsiCo. Originally created and developed in 1893 by Caleb Bradham and introduced as Brad's Drink, it was renamed as Pepsi-Cola in 1898, and then shortened to Pepsi in 1961"), GroceryItem(itemName: "Mountain Dew", itemImage: "dew", itemInfo: "Mountain Dewis a carbonated soft drink brand produced and owned by PepsiCo. The original formula was invented in 1940 by Tennessee beverage bottlers Barney and Ally Hartman. A revised formula was created by Bill Bridgforth in 1958. The rights to this formula were obtained by the Tip Corporation of Marion, Virginia.William H. Bill Jones of the Tip Corporation further refined the formula, launching that version of Mountain Dew in 1961."), GroceryItem(itemName: "Dr Pepper", itemImage: "pepper", itemInfo: "Dr Pepper is a carbonated soft drink. It was created in the 1880s by pharmacist Charles Alderton in Waco, Texas, and first served around 1885. Dr Pepper was first nationally marketed in the United States in 1904, and is now also sold in Europe, Asia, North and South America. In Australia, New Zealand and South Africa, Dr Pepper is sold as an imported good. Variants include Diet Dr Pepper and, beginning in the 2000s, a line of additional flavors."), GroceryItem(itemName: "Zero Coca Cola", itemImage: "zero", itemInfo: "Dr Pepper is a carbonated soft drink. It was created in the 1880s by pharmacist Charles Alderton in Waco, Texas, and first served around 1885. Dr Pepper was first nationally marketed in the United States in 1904, and is now also sold in Europe, Asia, North and South America. In Australia, New Zealand and South Africa, Dr Pepper is sold as an imported good. Variants include Diet Dr Pepper and, beginning in the 2000s, a line of additional flavors.")] )

let groceryitem5 = Grocery( section: "Bakery Items", items_Array: [GroceryItem(itemName: "Bagel", itemImage: "beagels", itemInfo: "A bagel is a bread product originating in the Jewish communities of Poland. It is traditionally shaped by hand into the form of a ring from yeasted wheat dough, roughly hand-sized, that is first boiled for a short time in water and then baked."), GroceryItem(itemName: "Rolls", itemImage: "roll", itemInfo: "A roll is a small, usually round or oblong individual loaf of bread served as a meal accompaniment. Rolls can be served and eaten whole or are also commonly cut and filled – the result of doing "), GroceryItem(itemName: "DoughNuts", itemImage: "doughnuts", itemInfo: "A doughnut or donut is a type of food made from leavened fried dough. It is popular in many countries and is prepared in various forms as a sweet snack that can be homemade or purchased in bakeries, supermarkets, food stalls, and franchised specialty vendors."), GroceryItem(itemName: "Danish", itemImage: "danish", itemInfo: "A Danish pastry, sometimes shortened to just Danish, is a multilayered, laminated sweet pastry in the viennoiserie tradition. The concept was brought to Denmark by Austrian bakers, where the recipe was partly changed and accommodated by the Danes to their liking, and has since developed into a Danish specialty."), GroceryItem(itemName: "Coffee Cake", itemImage: "coffe", itemInfo: "Coffee cake may refer to a sponge cake flavored with coffee or, in the United States, a sweet cake intended to be eaten with coffee or tea. A coffee-flavored cake is typically baked in a circular shape with two layers separated by coffee butter icing, which may also cover the top of the cake")] )


let grocerys = [groceryitem1, groceryitem2, groceryitem3, groceryitem4, groceryitem5]
